version: '3.8'

services:
  fastapi:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - fastmcp
    env_file:
      - routes/.env

  fastmcp:
    build: .
    command: python routes/MCP/main.py
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    env_file:
      - routes/.env
